"use server";

import { createAdminClient } from "@/lib/supabase/admin";
import { getClientAndUser } from "@/lib/supabase/get-client-and-user";
import { getCoupleAccess } from "@/lib/partner-invites";
import { revalidatePath } from "next/cache";
import { completeDate } from "@/app/actions/complete-date";

export interface DatePhoto {
  id: string;
  date_idea_id: string;
  profile_id: string;
  uploader_user_id: string;
  r2_key: string | null;
  skipped: boolean;
  created_at: string;
}

async function tryCompleteIfBothDone(
  admin: ReturnType<typeof createAdminClient>,
  profileId: string,
  dateIdeaId: string
): Promise<boolean> {
  const [{ count: memberCount }, { count: photoCount }] = await Promise.all([
    admin
      .from("couple_members")
      .select("*", { count: "exact", head: true })
      .eq("profile_id", profileId),
    admin
      .from("date_photos")
      .select("*", { count: "exact", head: true })
      .eq("date_idea_id", dateIdeaId)
      .eq("profile_id", profileId),
  ]);

  if ((photoCount ?? 0) < (memberCount ?? 2)) return false;

  try {
    await completeDate();
  } catch (err) {
    const msg = err instanceof Error ? err.message : "";
    // Other partner already completed — treat as done
    if (msg.includes("No active revealed date found")) return true;
    throw err;
  }
  return true;
}

export async function savePhoto(
  dateIdeaId: string,
  r2Key: string
): Promise<{ error?: string; completed?: boolean }> {
  const { user } = await getClientAndUser();
  if (!user) return { error: "Unauthorized" };

  const admin = createAdminClient();
  const access = await getCoupleAccess(admin, user.id);

  // Validate dateIdeaId is this couple's currently-revealed date (not historical).
  const { data: activeIdea } = await admin
    .from("date_ideas")
    .select("id")
    .eq("id", dateIdeaId)
    .eq("user_id", access.profileId)
    .eq("status", "revealed")
    .single();
  if (!activeIdea) return { error: "Date not found or not active" };

  // Validate r2Key matches the exact pattern generated by the presign route.
  // Prevents callers from attaching arbitrary R2 paths without a real upload.
  const keyPattern = new RegExp(
    `^photos/${access.profileId}/${dateIdeaId}/${user.id}_\\d+\\.jpg$`
  );
  if (!keyPattern.test(r2Key)) return { error: "Invalid photo key" };

  const { error } = await admin.from("date_photos").insert({
    date_idea_id: dateIdeaId,
    profile_id: access.profileId,
    uploader_user_id: user.id,
    r2_key: r2Key,
    skipped: false,
  });

  if (error) return { error: error.message };

  const completed = await tryCompleteIfBothDone(admin, access.profileId, dateIdeaId);
  revalidatePath("/dashboard");
  return { completed };
}

export async function skipPhoto(
  dateIdeaId: string
): Promise<{ error?: string; completed?: boolean }> {
  const { user } = await getClientAndUser();
  if (!user) return { error: "Unauthorized" };

  const admin = createAdminClient();
  const access = await getCoupleAccess(admin, user.id);

  // Validate dateIdeaId is this couple's currently-revealed date (not historical).
  const { data: activeIdea } = await admin
    .from("date_ideas")
    .select("id")
    .eq("id", dateIdeaId)
    .eq("user_id", access.profileId)
    .eq("status", "revealed")
    .single();
  if (!activeIdea) return { error: "Date not found or not active" };

  // ignoreDuplicates keeps existing real photos if user already uploaded
  const { error } = await admin.from("date_photos").upsert(
    {
      date_idea_id: dateIdeaId,
      profile_id: access.profileId,
      uploader_user_id: user.id,
      r2_key: null,
      skipped: true,
    },
    { onConflict: "date_idea_id,uploader_user_id", ignoreDuplicates: true }
  );

  if (error) return { error: error.message };

  const completed = await tryCompleteIfBothDone(admin, access.profileId, dateIdeaId);
  revalidatePath("/dashboard");
  return { completed };
}

export async function getPhotosForDate(dateIdeaId: string): Promise<DatePhoto[]> {
  const { user } = await getClientAndUser();
  if (!user) return [];

  const admin = createAdminClient();
  const access = await getCoupleAccess(admin, user.id);

  const { data } = await admin
    .from("date_photos")
    .select("id, date_idea_id, profile_id, uploader_user_id, r2_key, skipped, created_at")
    .eq("date_idea_id", dateIdeaId)
    .eq("profile_id", access.profileId)
    .order("created_at", { ascending: true });

  return (data ?? []) as DatePhoto[];
}

export interface CompletedDateWithPhotos {
  id: string;
  idea: Record<string, unknown>;
  revealed_at: string | null;
  photos: DatePhoto[];
}

export async function getDateHistory(): Promise<CompletedDateWithPhotos[]> {
  const { user } = await getClientAndUser();
  if (!user) return [];

  const admin = createAdminClient();
  const access = await getCoupleAccess(admin, user.id);

  const { data: ideas } = await admin
    .from("date_ideas")
    .select("id, idea, revealed_at")
    .eq("user_id", access.profileId)
    .eq("status", "completed")
    .order("revealed_at", { ascending: false });

  if (!ideas?.length) return [];

  const ideaIds = ideas.map((i) => i.id);
  const { data: photos } = await admin
    .from("date_photos")
    .select("id, date_idea_id, profile_id, uploader_user_id, r2_key, skipped, created_at")
    .in("date_idea_id", ideaIds)
    .eq("profile_id", access.profileId)
    .eq("skipped", false);

  const photosByDate = new Map<string, DatePhoto[]>();
  for (const p of photos ?? []) {
    const list = photosByDate.get(p.date_idea_id) ?? [];
    list.push(p as DatePhoto);
    photosByDate.set(p.date_idea_id, list);
  }

  return ideas.map((idea) => ({
    id: idea.id,
    idea: idea.idea as Record<string, unknown>,
    revealed_at: idea.revealed_at,
    photos: photosByDate.get(idea.id) ?? [],
  }));
}
