"use server";

import { createAdminClient } from "@/lib/supabase/admin";
import { getClientAndUser } from "@/lib/supabase/get-client-and-user";
import { getCoupleAccess } from "@/lib/partner-invites";
import { revalidatePath } from "next/cache";
import { completeDate } from "@/app/actions/complete-date";
import { HeadObjectCommand, DeleteObjectCommand } from "@aws-sdk/client-s3";
import { r2, R2_BUCKET } from "@/lib/r2";
import { isPlusPlan } from "@/lib/plans";

const MAX_PHOTO_BYTES = 5 * 1024 * 1024; // 5 MB

export interface DatePhoto {
  id: string;
  date_idea_id: string;
  profile_id: string;
  uploader_user_id: string;
  r2_key: string | null;
  skipped: boolean;
  created_at: string;
}

async function tryCompleteIfBothDone(
  admin: ReturnType<typeof createAdminClient>,
  profileId: string,
  dateIdeaId: string
): Promise<boolean> {
  const { data: idea } = await admin
    .from("date_ideas")
    .select("location_type")
    .eq("id", dateIdeaId)
    .single();

  const isHomeDate = idea?.location_type === "home";

  if (isHomeDate) {
    // Home dates: all members must decide (upload or skip) before completing.
    // At least one real (non-skipped) photo is required to count the date.
    const [{ data: members }, { count: totalPhotoCount }, { count: realPhotoCount }] = await Promise.all([
      admin.from("couple_members").select("user_id").eq("profile_id", profileId),
      admin.from("date_photos").select("*", { count: "exact", head: true })
        .eq("date_idea_id", dateIdeaId).eq("profile_id", profileId),
      admin.from("date_photos").select("*", { count: "exact", head: true })
        .eq("date_idea_id", dateIdeaId).eq("profile_id", profileId).eq("skipped", false),
    ]);

    const memberCount = members?.length ?? 0;
    if (memberCount === 0) return false;
    if ((totalPhotoCount ?? 0) < memberCount) return false; // not all decided yet
    if ((realPhotoCount ?? 0) === 0) return false; // both skipped — BothSkippedScreen handles this

    try {
      await completeDate();
    } catch (err) {
      const msg = err instanceof Error ? err.message : "";
      if (msg.includes("No active revealed date found")) return true;
      throw err;
    }
    return true;
  }

  // Outside dates: every member who physically checked in (not skipped) must
  // have a photo row (upload OR skip) before completion.
  const [{ data: members }, { data: profile }] = await Promise.all([
    admin.from("couple_members").select("user_id, role").eq("profile_id", profileId),
    admin
      .from("profiles")
      .select("checkin_owner_skipped, checkin_partner_skipped")
      .eq("id", profileId)
      .single(),
  ]);

  if (!members?.length) return false;

  const requiredUserIds = members
    .filter((m) => {
      if (m.role === "owner") return !profile?.checkin_owner_skipped;
      return !profile?.checkin_partner_skipped;
    })
    .map((m) => m.user_id);

  if (requiredUserIds.length === 0) return false;

  const { count: photoCount } = await admin
    .from("date_photos")
    .select("*", { count: "exact", head: true })
    .eq("date_idea_id", dateIdeaId)
    .eq("profile_id", profileId)
    .in("uploader_user_id", requiredUserIds);

  if ((photoCount ?? 0) < requiredUserIds.length) return false;

  try {
    await completeDate();
  } catch (err) {
    const msg = err instanceof Error ? err.message : "";
    if (msg.includes("No active revealed date found")) return true;
    // RPC guard fired due to a race between our check and the DB write.
    // Treat as "not yet complete" rather than a 500.
    if (msg.includes("All members must submit") || msg.includes("Waiting for all partners")) return false;
    throw err;
  }
  return true;
}

const XP_PHOTO = 25;

export async function savePhoto(
  dateIdeaId: string,
  r2Key: string
): Promise<{ error?: string; completed?: boolean; xpGained?: number }> {
  const { user } = await getClientAndUser();
  if (!user) return { error: "Unauthorized" };

  const admin = createAdminClient();
  const access = await getCoupleAccess(admin, user.id);

  // Validate dateIdeaId is this couple's currently-revealed date (not historical).
  const { data: activeIdea } = await admin
    .from("date_ideas")
    .select("id, location_type")
    .eq("id", dateIdeaId)
    .eq("user_id", access.profileId)
    .eq("status", "revealed")
    .single();
  if (!activeIdea) return { error: "Date not found or not active" };

  // Block users who skipped check-in (defense-in-depth vs stale presign URLs)
  const { data: checkinProfile } = await admin
    .from("profiles")
    .select("checkin_owner_skipped, checkin_partner_skipped, plan_type")
    .eq("id", access.profileId)
    .single();
  const mySkipped =
    access.role === "owner"
      ? checkinProfile?.checkin_owner_skipped
      : checkinProfile?.checkin_partner_skipped;
  if (mySkipped) return { error: "Check-in required to upload photo" };

  // Validate r2Key matches the exact pattern generated by the presign route.
  // Prevents callers from attaching arbitrary R2 paths without a real upload.
  const keyPattern = new RegExp(
    `^photos/${access.profileId}/${dateIdeaId}/${user.id}_\\d+\\.jpg$`
  );
  if (!keyPattern.test(r2Key)) return { error: "Invalid photo key" };

  // Verify the object actually exists in R2 and is within the size cap.
  // Rejects keys submitted without a real upload and enforces the 5 MB limit.
  try {
    const head = await r2.send(new HeadObjectCommand({ Bucket: R2_BUCKET, Key: r2Key }));
    if (!head.ContentLength || head.ContentLength === 0) return { error: "Photo upload appears empty" };
    if (head.ContentLength > MAX_PHOTO_BYTES) {
      // Delete the oversized object so it doesn't linger in R2 storage.
      await r2.send(new DeleteObjectCommand({ Bucket: R2_BUCKET, Key: r2Key })).catch(() => {});
      return { error: "Photo exceeds 5 MB limit" };
    }
  } catch {
    return { error: "Photo not found — upload may have failed" };
  }

  const { error } = await admin.from("date_photos").insert({
    date_idea_id: dateIdeaId,
    profile_id: access.profileId,
    uploader_user_id: user.id,
    r2_key: r2Key,
    skipped: false,
  });

  if (error) return { error: error.message };

  // For home dates, photo upload IS the check-in signal — mirror what skipPhoto
  // does so complete_date's dual-check-in guard doesn't block completion.
  if (activeIdea.location_type === "home") {
    const nowIso = new Date().toISOString();
    const checkinFlag =
      access.role === "owner"
        ? { checkin_owner_at: nowIso }
        : { checkin_partner_at: nowIso };
    await admin.from("profiles").update(checkinFlag).eq("id", access.profileId);
  }

  let xpGained = 0;
  if (isPlusPlan(checkinProfile?.plan_type)) {
    // award_xp increments total_xp atomically in SQL — no read-modify-write race.
    const { error: xpError } = await admin.rpc("award_xp", {
      p_profile_id: access.profileId,
      p_xp: XP_PHOTO,
    });
    if (xpError) {
      console.error(`[audit] save-photo: xp update failed uid=${user.id} msg=${xpError.message}`);
    } else {
      xpGained = XP_PHOTO;
    }
  }

  const completed = await tryCompleteIfBothDone(admin, access.profileId, dateIdeaId);
  revalidatePath("/dashboard");
  return { completed, xpGained };
}

export async function skipPhoto(
  dateIdeaId: string
): Promise<{ error?: string; completed?: boolean }> {
  const { user } = await getClientAndUser();
  if (!user) return { error: "Unauthorized" };

  const admin = createAdminClient();
  const access = await getCoupleAccess(admin, user.id);

  // Validate dateIdeaId is this couple's currently-revealed date (not historical).
  const { data: activeIdea } = await admin
    .from("date_ideas")
    .select("id, location_type")
    .eq("id", dateIdeaId)
    .eq("user_id", access.profileId)
    .eq("status", "revealed")
    .single();
  if (!activeIdea) return { error: "Date not found or not active" };

  // Block users who skipped check-in from the photo flow entirely
  const { data: checkinProfile } = await admin
    .from("profiles")
    .select("checkin_owner_skipped, checkin_partner_skipped")
    .eq("id", access.profileId)
    .single();
  const mySkipped =
    access.role === "owner"
      ? checkinProfile?.checkin_owner_skipped
      : checkinProfile?.checkin_partner_skipped;
  if (mySkipped) return { error: "Check-in required to complete photo step" };

  // ignoreDuplicates keeps existing real photos if user already uploaded
  const { error } = await admin.from("date_photos").upsert(
    {
      date_idea_id: dateIdeaId,
      profile_id: access.profileId,
      uploader_user_id: user.id,
      r2_key: null,
      skipped: true,
    },
    { onConflict: "date_idea_id,uploader_user_id", ignoreDuplicates: true }
  );

  if (error) return { error: error.message };

  // For home dates, mirror the photo-skip as a check-in skip so the
  // BothSkippedScreen can detect when both partners opted out.
  if (activeIdea.location_type === "home") {
    const nowIso = new Date().toISOString();
    const skipFlag =
      access.role === "owner"
        ? { checkin_owner_at: nowIso, checkin_owner_skipped: true }
        : { checkin_partner_at: nowIso, checkin_partner_skipped: true };
    await admin.from("profiles").update(skipFlag).eq("id", access.profileId);
  }

  const completed = await tryCompleteIfBothDone(admin, access.profileId, dateIdeaId);
  revalidatePath("/dashboard");
  return { completed };
}

export async function getPhotosForDate(dateIdeaId: string): Promise<DatePhoto[]> {
  const { user } = await getClientAndUser();
  if (!user) return [];

  const admin = createAdminClient();
  const access = await getCoupleAccess(admin, user.id);

  const { data } = await admin
    .from("date_photos")
    .select("id, date_idea_id, profile_id, uploader_user_id, r2_key, skipped, created_at")
    .eq("date_idea_id", dateIdeaId)
    .eq("profile_id", access.profileId)
    .order("created_at", { ascending: true });

  return (data ?? []) as DatePhoto[];
}

export interface CompletedDateWithPhotos {
  id: string;
  idea: Record<string, unknown>;
  revealed_at: string | null;
  photos: DatePhoto[];
}

export async function getDateHistory(): Promise<CompletedDateWithPhotos[]> {
  const { user } = await getClientAndUser();
  if (!user) return [];

  const admin = createAdminClient();
  const access = await getCoupleAccess(admin, user.id);

  const { data: ideas } = await admin
    .from("date_ideas")
    .select("id, idea, revealed_at")
    .eq("user_id", access.profileId)
    .eq("status", "completed")
    .order("revealed_at", { ascending: false });

  if (!ideas?.length) return [];

  const ideaIds = ideas.map((i) => i.id);
  const { data: photos } = await admin
    .from("date_photos")
    .select("id, date_idea_id, profile_id, uploader_user_id, r2_key, skipped, created_at")
    .in("date_idea_id", ideaIds)
    .eq("profile_id", access.profileId)
    .eq("skipped", false);

  const photosByDate = new Map<string, DatePhoto[]>();
  for (const p of photos ?? []) {
    const list = photosByDate.get(p.date_idea_id) ?? [];
    list.push(p as DatePhoto);
    photosByDate.set(p.date_idea_id, list);
  }

  return ideas
    .map((idea) => ({
      id: idea.id,
      idea: idea.idea as Record<string, unknown>,
      revealed_at: idea.revealed_at,
      photos: photosByDate.get(idea.id) ?? [],
    }))
    .filter((d) => d.photos.length > 0);
}
