/**
 * Known disposable / temporary email domains.
 * Add new entries here as needed — keep alphabetical within each group.
 */
const DISPOSABLE_DOMAINS = new Set([
  // --- 10-minute / short-lived inboxes ---
  "10minutemail.com",
  "10minutemail.net",
  "10minemail.com",
  "20minutemail.com",
  "tempr.email",
  "throwam.com",

  // --- Guerrilla Mail network ---
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.info",
  "grr.la",
  "sharklasers.com",
  "spam4.me",
  "guerrillamailblock.com",

  // --- Mailinator family ---
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinater.com",
  "suremail.info",
  "spamherelots.com",
  "spamhereplease.com",
  "mailinator2.com",
  "tradermail.info",

  // --- Yopmail family ---
  "yopmail.com",
  "yopmail.fr",
  "cool.fr.nf",
  "jetable.fr.nf",
  "nospam.ze.tc",
  "nomail.xl.cx",
  "mega.zik.dj",
  "speed.1s.fr",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",

  // --- Temp-mail / throwaway services ---
  "tempmail.com",
  "tempmail.net",
  "tempmail.org",
  "temp-mail.org",
  "temp-mail.io",
  "tempinbox.com",
  "tempemail.com",
  "tempemail.net",
  "throwaway.email",
  "throwam.com",
  "throwbin.io",

  // --- Dispostable / Trashmail ---
  "dispostable.com",
  "trashmail.com",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.at",
  "trashmail.io",
  "trashmail.xyz",

  // --- Fake inbox services ---
  "fakeinbox.com",
  "fakeinbox.net",
  "fakemail.fr",
  "mailnull.com",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",

  // --- Maildrop / Mailnesia ---
  "maildrop.cc",
  "mailnesia.com",

  // --- Spambox / Nada ---
  "spambox.us",
  "nada.email",
  "nada.ltd",

  // --- Other popular services ---
  "byom.de",
  "cuvox.de",
  "dayrep.com",
  "delikkt.de",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "harakirimail.com",
  "hatespam.org",
  "inoutmail.de",
  "inoutmail.eu",
  "inoutmail.info",
  "inoutmail.net",
  "jetable.com",
  "jetable.net",
  "jetable.org",
  "kasmail.com",
  "klassmaster.com",
  "klzlk.com",
  "koszmail.pl",
  "kulturbeutel.de",
  "kurzepost.de",
  "lhsdv.com",
  "ligsb.com",
  "lookugly.com",
  "lortemail.dk",
  "lovemeleaveme.com",
  "lr7.us",
  "lukemail.info",
  "lyricspad.net",
  "m4ilweb.info",
  "mail.mezimages.net",
  "mail1a.de",
  "mail2rss.org",
  "mail333.com",
  "mailbidon.com",
  "mailbiz.biz",
  "mailblocks.com",
  "mailbucket.org",
  "mailchop.com",
  "mailexpire.com",
  "mailfs.com",
  "mailguard.me",
  "mailin8r.com",
  "mailinblack.com",
  "mailme.lv",
  "mailme24.com",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnew.com",
  "mailpick.biz",
  "mailrock.biz",
  "mailscrap.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslite.com",
  "mailsucker.net",
  "mailtome.de",
  "mailtothis.com",
  "mailzilla.com",
  "mailzilla.org",
  "mbx.cc",
  "mega.zik.dj",
  "meltmail.com",
  "mierdamail.com",
  "mintemail.com",
  "misterpinball.de",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "mt2009.com",
  "mt2014.com",
  "mx0.wwwnew.eu",
  "mycleaninbox.net",
  "mypartyclip.de",
  "myphantomemail.com",
  "mysamp.de",
  "mytempemail.com",
  "mytempmail.com",
  "mytrashmail.com",
  "neomailbox.com",
  "nepwelt.de",
  "nervmich.net",
  "nervtmich.net",
  "netmails.com",
  "netmails.net",
  "noblepioneer.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nospamfor.us",
  "nospammail.net",
  "notmailinator.com",
  "nowmymail.com",
  "objectmail.com",
  "obobbo.com",
  "odaymail.com",
  "oneoffemail.com",
  "onewaymail.com",
  "online.ms",
  "oopi.org",
  "opayq.com",
  "ordinaryamerican.net",
  "owlpic.com",
]);

/**
 * Returns true if the email's domain is a known disposable email provider.
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase().trim();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}
